# Generated by Django 4.2.7 on 2026-02-07 15:21

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('employer', 'Employer'), ('user', 'User')], default='user', help_text='User role for access control', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('profile_picture', models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to='profiles/')),
                ('bio', models.TextField(blank=True, help_text='Short bio about the user', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(help_text='School/University name', max_length=200)),
                ('degree', models.CharField(help_text='Degree type (e.g., Bachelor of Science, Master of Arts)', max_length=100)),
                ('field_of_study', models.CharField(help_text='Field of study (e.g., Computer Science, Business)', max_length=100)),
                ('start_date', models.DateField(help_text='Education start date')),
                ('end_date', models.DateField(blank=True, help_text='Education end date (null if ongoing)', null=True)),
                ('is_current', models.BooleanField(default=False, help_text='Whether this education is ongoing')),
                ('description', models.TextField(blank=True, help_text='Additional details (honors, achievements, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'db_table': 'user_education',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Project title', max_length=200)),
                ('description', models.TextField(help_text='Project description')),
                ('url', models.URLField(blank=True, help_text='Project URL (GitHub, website, etc.)')),
                ('technologies', models.CharField(blank=True, help_text='Technologies used (comma-separated)', max_length=500)),
                ('start_date', models.DateField(blank=True, help_text='Project start date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Project end date', null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Whether this is a featured project')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolio',
                'db_table': 'user_portfolio',
                'ordering': ['-is_featured', '-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Personal notes about this job')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Saved Job',
                'verbose_name_plural': 'Saved Jobs',
                'db_table': 'saved_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(help_text='Company name', max_length=200)),
                ('position', models.CharField(help_text='Job title/position', max_length=200)),
                ('start_date', models.DateField(help_text='Employment start date')),
                ('end_date', models.DateField(blank=True, help_text='Employment end date (null if current job)', null=True)),
                ('is_current', models.BooleanField(default=False, help_text='Whether this is the current job')),
                ('description', models.TextField(blank=True, help_text='Job description and responsibilities')),
                ('location', models.CharField(blank=True, help_text='Job location', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who has this work experience', on_delete=django.db.models.deletion.CASCADE, related_name='work_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work History',
                'verbose_name_plural': 'Work History',
                'db_table': 'user_work_history',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_job_alerts', models.BooleanField(default=True, help_text='Receive email notifications for job alerts')),
                ('email_application_updates', models.BooleanField(default=True, help_text='Receive email notifications for application updates')),
                ('email_new_jobs', models.BooleanField(default=False, help_text='Receive email notifications for new jobs matching saved searches')),
                ('email_newsletter', models.BooleanField(default=False, help_text='Receive newsletter emails')),
                ('alert_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', help_text='Frequency of job alert emails', max_length=20)),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('employers', 'Employers Only'), ('private', 'Private')], default='employers', help_text='Profile visibility level', max_length=20)),
                ('show_email', models.BooleanField(default=False, help_text='Show email address on profile')),
                ('show_phone', models.BooleanField(default=False, help_text='Show phone number on profile')),
                ('show_location', models.BooleanField(default=True, help_text='Show location on profile')),
                ('resume_visibility', models.CharField(choices=[('public', 'Public'), ('employers', 'Employers Only'), ('private', 'Private')], default='employers', help_text='Resume visibility level', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User preferences', on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preferences',
                'verbose_name_plural': 'User Preferences',
                'db_table': 'user_preferences',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('twitter', 'Twitter'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('website', 'Personal Website'), ('other', 'Other')], help_text='Social media platform', max_length=20)),
                ('url', models.URLField(help_text='Social media profile URL')),
                ('is_public', models.BooleanField(default=True, help_text='Whether this link is publicly visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns this social link', on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'db_table': 'user_social_links',
                'ordering': ['platform'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Skill name (e.g., Python, JavaScript)', max_length=100)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', help_text='Skill proficiency level', max_length=20)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, help_text='Years of experience with this skill', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns this skill', on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'db_table': 'user_skills',
                'ordering': ['-updated_at'],
            },
        ),
    ]
