# Generated by Django 4.2.7 on 2026-02-07 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedjob',
            name='job',
            field=models.ForeignKey(help_text='Saved job', on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='savedjob',
            name='user',
            field=models.ForeignKey(help_text='User who saved this job', on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='user',
            field=models.ForeignKey(help_text='User who owns this portfolio item', on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='education',
            name='user',
            field=models.ForeignKey(help_text='User who has this education', on_delete=django.db.models.deletion.CASCADE, related_name='education', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='workhistory',
            index=models.Index(fields=['user', '-start_date'], name='user_work_h_user_id_395e70_idx'),
        ),
        migrations.AddIndex(
            model_name='sociallink',
            index=models.Index(fields=['user', 'platform'], name='user_social_user_id_8dfd6a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sociallink',
            unique_together={('user', 'platform')},
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['user', 'name'], name='user_skills_user_id_2f316c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='savedjob',
            index=models.Index(fields=['user', '-created_at'], name='saved_jobs_user_id_08012b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedjob',
            unique_together={('user', 'job')},
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['user', '-is_featured'], name='user_portfo_user_id_68c03d_idx'),
        ),
        migrations.AddIndex(
            model_name='education',
            index=models.Index(fields=['user', '-start_date'], name='user_educat_user_id_1ffa1e_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='users_role_a8f2ba_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='users_usernam_baeb4b_idx'),
        ),
    ]
