# Generated by Django 4.2.7 on 2026-02-07 15:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(help_text='Cover letter for the application')),
                ('resume', models.FileField(help_text='Resume file (PDF, DOC, DOCX, max 5MB)', upload_to='resumes/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Application status', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the application was reviewed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the application (employer/admin only)', null=True)),
                ('is_withdrawn', models.BooleanField(db_index=True, default=False, help_text='Whether application has been withdrawn')),
                ('withdrawn_at', models.DateTimeField(blank=True, help_text='When application was withdrawn', null=True)),
                ('withdrawal_reason', models.TextField(blank=True, help_text='Reason for withdrawal')),
                ('applicant', models.ForeignKey(help_text='User applying for the job', on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'db_table': 'applications',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Category name (e.g., "Software Development")', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the category', null=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of the name (auto-generated)', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category for hierarchical organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='jobs.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='Job title', max_length=200)),
                ('description', models.TextField(help_text='Full job description')),
                ('requirements', models.TextField(help_text='Job requirements and qualifications')),
                ('location', models.CharField(db_index=True, help_text='Job location', max_length=100)),
                ('job_type', models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('freelance', 'Freelance')], db_index=True, default='full-time', help_text='Type of employment', max_length=20)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum salary', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum salary', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], db_index=True, default='draft', help_text='Job posting status', max_length=20)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Admin approval status', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, help_text='When this job was approved', null=True)),
                ('scheduled_publish_date', models.DateTimeField(blank=True, db_index=True, help_text='Schedule job to be published at this date/time', null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='Job expiration date (auto-closes after this)', null=True)),
                ('auto_renew', models.BooleanField(default=False, help_text='Automatically renew job when it expires')),
                ('renewal_count', models.PositiveIntegerField(default=0, help_text='Number of times this job has been renewed')),
                ('application_deadline', models.DateField(blank=True, help_text='Application deadline date', null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Whether this job is featured')),
                ('views_count', models.PositiveIntegerField(default=0, help_text='Number of times this job has been viewed')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin who approved this job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_jobs', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(help_text='Job category', on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.category')),
                ('employer', models.ForeignKey(help_text='Job employer/creator', on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for the saved search', max_length=100)),
                ('search_query', models.CharField(help_text='Search query text', max_length=255)),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Applied filters (category, location, etc.)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this saved search is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_searched_at', models.DateTimeField(blank=True, help_text='When this search was last executed', null=True)),
                ('user', models.ForeignKey(help_text='User who saved the search', on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Search',
                'verbose_name_plural': 'Saved Searches',
                'db_table': 'saved_searches',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Question text')),
                ('question_type', models.CharField(choices=[('text', 'Text'), ('multiple_choice', 'Multiple Choice'), ('yes_no', 'Yes/No'), ('number', 'Number'), ('date', 'Date')], default='text', help_text='Type of question', max_length=20)),
                ('is_required', models.BooleanField(default=True, help_text='Whether this question is required')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('options', models.JSONField(blank=True, default=list, help_text='Options for multiple choice questions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(help_text='Job this question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='screening_questions', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Screening Question',
                'verbose_name_plural': 'Screening Questions',
                'db_table': 'screening_questions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(help_text='Answer text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(help_text='Application this answer belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='screening_answers', to='jobs.application')),
                ('question', models.ForeignKey(help_text='Question being answered', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='jobs.screeningquestion')),
            ],
            options={
                'verbose_name': 'Screening Answer',
                'verbose_name_plural': 'Screening Answers',
                'db_table': 'screening_answers',
            },
        ),
        migrations.CreateModel(
            name='PopularSearchTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(db_index=True, help_text='Search term', max_length=255, unique=True)),
                ('search_count', models.PositiveIntegerField(default=1, help_text='Number of times this term has been searched')),
                ('last_searched_at', models.DateTimeField(auto_now=True, db_index=True, help_text='When this term was last searched')),
                ('first_searched_at', models.DateTimeField(auto_now_add=True, help_text='When this term was first searched')),
            ],
            options={
                'verbose_name': 'Popular Search Term',
                'verbose_name_plural': 'Popular Search Terms',
                'db_table': 'popular_search_terms',
                'ordering': ['-search_count', '-last_searched_at'],
                'indexes': [models.Index(fields=['-search_count'], name='popular_sea_search__407f15_idx'), models.Index(fields=['-last_searched_at'], name='popular_sea_last_se_15d9a2_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the viewer', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='User agent string', max_length=255)),
                ('referrer', models.URLField(blank=True, help_text='Referrer URL')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('job', models.ForeignKey(help_text='Job that was viewed', on_delete=django.db.models.deletion.CASCADE, related_name='views', to='jobs.job')),
                ('user', models.ForeignKey(blank=True, help_text='User who viewed the job (null for anonymous)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job View',
                'verbose_name_plural': 'Job Views',
                'db_table': 'job_views',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='JobShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('email', 'Email'), ('link', 'Link'), ('social', 'Social Media'), ('other', 'Other')], help_text='Sharing method', max_length=20)),
                ('shared_with', models.CharField(blank=True, help_text='Email or identifier of who it was shared with', max_length=255)),
                ('shared_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('job', models.ForeignKey(help_text='Job that was shared', on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='jobs.job')),
                ('user', models.ForeignKey(blank=True, help_text='User who shared the job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Share',
                'verbose_name_plural': 'Job Shares',
                'db_table': 'job_shares',
                'ordering': ['-shared_at'],
            },
        ),
        migrations.CreateModel(
            name='JobRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, help_text='Recommendation score (0.0 to 1.0)')),
                ('reason', models.CharField(blank=True, help_text='Reason for recommendation', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('viewed', models.BooleanField(default=False, help_text='Whether user has viewed this recommendation')),
                ('clicked', models.BooleanField(default=False, help_text='Whether user clicked on this recommendation')),
                ('job', models.ForeignKey(help_text='Recommended job', on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='jobs.job')),
                ('user', models.ForeignKey(help_text='User who receives the recommendation', on_delete=django.db.models.deletion.CASCADE, related_name='job_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Recommendation',
                'verbose_name_plural': 'Job Recommendations',
                'db_table': 'job_recommendations',
                'ordering': ['-score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.PositiveIntegerField(default=0, help_text='Total number of views')),
                ('unique_views', models.PositiveIntegerField(default=0, help_text='Number of unique viewers')),
                ('total_applications', models.PositiveIntegerField(default=0, help_text='Total number of applications')),
                ('shares_count', models.PositiveIntegerField(default=0, help_text='Number of times job was shared')),
                ('saved_count', models.PositiveIntegerField(default=0, help_text='Number of times job was saved')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(help_text='Job analytics', on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Job Analytics',
                'verbose_name_plural': 'Job Analytics',
                'db_table': 'job_analytics',
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(help_text='Interview scheduled date and time')),
                ('duration', models.PositiveIntegerField(default=60, help_text='Interview duration in minutes')),
                ('interview_type', models.CharField(choices=[('phone', 'Phone'), ('video', 'Video'), ('in_person', 'In Person'), ('other', 'Other')], default='video', help_text='Type of interview', max_length=20)),
                ('location', models.CharField(blank=True, help_text='Interview location (for in-person)', max_length=255)),
                ('video_link', models.URLField(blank=True, help_text='Video call link (for video interviews)')),
                ('notes', models.TextField(blank=True, help_text='Interview notes')),
                ('is_confirmed', models.BooleanField(default=False, help_text='Whether interview is confirmed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(help_text='Application this interview is for', on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='jobs.application')),
                ('interviewer', models.ForeignKey(blank=True, help_text='Interviewer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interview',
                'verbose_name_plural': 'Interviews',
                'db_table': 'interviews',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Template description')),
                ('default_notes', models.TextField(blank=True, help_text='Default notes for applications using this template')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(help_text='Employer who owns this template', on_delete=django.db.models.deletion.CASCADE, related_name='application_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application Template',
                'verbose_name_plural': 'Application Templates',
                'db_table': 'application_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], help_text='Previous status', max_length=20, null=True)),
                ('new_status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], help_text='New status', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Reason for status change')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('application', models.ForeignKey(help_text='Application this history belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='jobs.application')),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who changed the status', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_status_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application Status History',
                'verbose_name_plural': 'Application Status Histories',
                'db_table': 'application_status_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_type', models.CharField(choices=[('application', 'Application'), ('screening', 'Screening'), ('interview', 'Interview'), ('assessment', 'Assessment'), ('offer', 'Offer'), ('hired', 'Hired'), ('rejected', 'Rejected')], help_text='Type of stage', max_length=20)),
                ('stage_name', models.CharField(help_text='Custom stage name', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Stage order')),
                ('is_completed', models.BooleanField(default=False, help_text='Whether this stage is completed')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When this stage was completed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Stage notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(help_text='Application this stage belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='jobs.application')),
            ],
            options={
                'verbose_name': 'Application Stage',
                'verbose_name_plural': 'Application Stages',
                'db_table': 'application_stages',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('direct', 'Direct Application'), ('referral', 'Referral'), ('job_board', 'Job Board'), ('social_media', 'Social Media'), ('email', 'Email Campaign'), ('other', 'Other')], default='direct', help_text='Source type', max_length=50)),
                ('referrer_url', models.URLField(blank=True, help_text='Referrer URL if applicable')),
                ('campaign', models.CharField(blank=True, help_text='Marketing campaign identifier', max_length=100)),
                ('utm_source', models.CharField(blank=True, help_text='UTM source parameter', max_length=100)),
                ('utm_medium', models.CharField(blank=True, help_text='UTM medium parameter', max_length=100)),
                ('utm_campaign', models.CharField(blank=True, help_text='UTM campaign parameter', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(help_text='Application source tracking', on_delete=django.db.models.deletion.CASCADE, related_name='source', to='jobs.application')),
            ],
            options={
                'verbose_name': 'Application Source',
                'verbose_name_plural': 'Application Sources',
                'db_table': 'application_sources',
            },
        ),
        migrations.CreateModel(
            name='ApplicationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(default=0.0, help_text='Overall score (0.0 to 100.0)')),
                ('experience_score', models.FloatField(default=0.0, help_text='Experience score')),
                ('skills_score', models.FloatField(default=0.0, help_text='Skills score')),
                ('education_score', models.FloatField(default=0.0, help_text='Education score')),
                ('screening_score', models.FloatField(default=0.0, help_text='Screening questions score')),
                ('notes', models.TextField(blank=True, help_text='Scoring notes')),
                ('scored_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(help_text='Application score', on_delete=django.db.models.deletion.CASCADE, related_name='score', to='jobs.application')),
                ('scored_by', models.ForeignKey(blank=True, help_text='User who scored this application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scored_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application Score',
                'verbose_name_plural': 'Application Scores',
                'db_table': 'application_scores',
                'ordering': ['-overall_score'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(help_text='Note content')),
                ('rating', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rating (1-5 stars)', null=True)),
                ('is_internal', models.BooleanField(default=True, help_text='Whether this note is internal (not visible to applicant)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(help_text='Application this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='application_notes', to='jobs.application')),
                ('author', models.ForeignKey(help_text='User who wrote the note', on_delete=django.db.models.deletion.CASCADE, related_name='application_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application Note',
                'verbose_name_plural': 'Application Notes',
                'db_table': 'application_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(help_text='Job being applied for', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='application',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Application template used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='jobs.applicationtemplate'),
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(db_index=True, help_text='Search query text', max_length=255)),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Applied filters (category, location, etc.)')),
                ('result_count', models.PositiveIntegerField(default=0, help_text='Number of results returned')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the searcher', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the search (null for anonymous)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search History',
                'verbose_name_plural': 'Search Histories',
                'db_table': 'search_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='search_hist_user_id_3ea0ad_idx'), models.Index(fields=['search_query', '-created_at'], name='search_hist_search__cd87a0_idx'), models.Index(fields=['-created_at'], name='search_hist_created_e154e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for the search alert', max_length=100)),
                ('search_query', models.CharField(help_text='Search query text', max_length=255)),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Applied filters (category, location, etc.)')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('immediate', 'Immediate')], default='daily', help_text='How often to check for new jobs', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this alert is active')),
                ('last_notified_at', models.DateTimeField(blank=True, help_text='When the user was last notified', null=True)),
                ('last_job_id', models.IntegerField(blank=True, help_text='ID of the last job found (to avoid duplicates)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('saved_search', models.ForeignKey(blank=True, help_text='Associated saved search (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='jobs.savedsearch')),
                ('user', models.ForeignKey(help_text='User who created the alert', on_delete=django.db.models.deletion.CASCADE, related_name='search_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search Alert',
                'verbose_name_plural': 'Search Alerts',
                'db_table': 'search_alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='search_aler_user_id_dd12cd_idx'), models.Index(fields=['frequency', 'is_active'], name='search_aler_frequen_a7cb86_idx'), models.Index(fields=['-created_at'], name='search_aler_created_11bea2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='screeningquestion',
            index=models.Index(fields=['job', 'order'], name='screening_q_job_id_0e8619_idx'),
        ),
        migrations.AddIndex(
            model_name='screeninganswer',
            index=models.Index(fields=['application', 'question'], name='screening_a_applica_805cc6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='screeninganswer',
            unique_together={('application', 'question')},
        ),
        migrations.AddIndex(
            model_name='savedsearch',
            index=models.Index(fields=['user', 'is_active'], name='saved_searc_user_id_2b1034_idx'),
        ),
        migrations.AddIndex(
            model_name='savedsearch',
            index=models.Index(fields=['-updated_at'], name='saved_searc_updated_44dc30_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedsearch',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='jobview',
            index=models.Index(fields=['job', '-viewed_at'], name='job_views_job_id_4ba144_idx'),
        ),
        migrations.AddIndex(
            model_name='jobview',
            index=models.Index(fields=['user', '-viewed_at'], name='job_views_user_id_932dd5_idx'),
        ),
        migrations.AddIndex(
            model_name='jobview',
            index=models.Index(fields=['-viewed_at'], name='job_views_viewed__c2bfd2_idx'),
        ),
        migrations.AddIndex(
            model_name='jobshare',
            index=models.Index(fields=['job', '-shared_at'], name='job_shares_job_id_b88125_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrecommendation',
            index=models.Index(fields=['user', '-score'], name='job_recomme_user_id_058038_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrecommendation',
            index=models.Index(fields=['job', '-score'], name='job_recomme_job_id_ef8f01_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobrecommendation',
            unique_together={('user', 'job')},
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', '-created_at'], name='jobs_status_70b954_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['category', 'location'], name='jobs_categor_e987e9_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['job_type', 'status'], name='jobs_job_typ_f035dd_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['salary_min', 'salary_max'], name='jobs_salary__0b1197_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_featured', 'status'], name='jobs_is_feat_c15b6d_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['application', 'scheduled_at'], name='interviews_applica_d4b49e_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['interviewer', 'scheduled_at'], name='interviews_intervi_62b98b_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['scheduled_at'], name='interviews_schedul_3fb753_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='categories_slug_b4303a_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='categories_parent__7983b2_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name', 'parent'], name='categories_name_f41296_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationtemplate',
            index=models.Index(fields=['employer', 'is_active'], name='application_employe_6d65a3_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationstatushistory',
            index=models.Index(fields=['application', '-changed_at'], name='application_applica_cea5fb_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationstatushistory',
            index=models.Index(fields=['changed_by', '-changed_at'], name='application_changed_1806ca_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationstage',
            index=models.Index(fields=['application', 'order'], name='application_applica_72c66b_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationstage',
            index=models.Index(fields=['application', 'is_completed'], name='application_applica_86cc75_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationsource',
            index=models.Index(fields=['source_type'], name='application_source__3b6fe2_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationsource',
            index=models.Index(fields=['utm_source', 'utm_medium'], name='application_utm_sou_a3fecb_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationscore',
            index=models.Index(fields=['-overall_score'], name='application_overall_5180ee_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationscore',
            index=models.Index(fields=['scored_by', '-scored_at'], name='application_scored__703568_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationnote',
            index=models.Index(fields=['application', '-created_at'], name='application_applica_3c9d60_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationnote',
            index=models.Index(fields=['author', '-created_at'], name='application_author__bcef11_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', '-applied_at'], name='application_status_92c333_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job', 'status'], name='application_job_id_606b4d_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applicant', 'status'], name='application_applica_e9ee09_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['is_withdrawn', '-applied_at'], name='application_is_with_9e45d8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('job', 'applicant')},
        ),
    ]
