# Generated by Django 4.2.7 on 2026-02-07 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_app_job_applications', models.BooleanField(default=True, help_text='Receive in-app notifications for job applications')),
                ('in_app_application_updates', models.BooleanField(default=True, help_text='Receive in-app notifications for application status updates')),
                ('in_app_new_jobs', models.BooleanField(default=True, help_text='Receive in-app notifications for new matching jobs')),
                ('in_app_messages', models.BooleanField(default=True, help_text='Receive in-app notifications for messages')),
                ('in_app_system', models.BooleanField(default=True, help_text='Receive in-app system notifications')),
                ('notification_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest')], default='immediate', help_text='Notification frequency preference', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User notification preferences', on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('failed_login', 'Failed Login'), ('suspicious_activity', 'Suspicious Activity'), ('rate_limit_exceeded', 'Rate Limit Exceeded'), ('unauthorized_access', 'Unauthorized Access'), ('api_key_abuse', 'API Key Abuse'), ('password_reset_attempt', 'Password Reset Attempt'), ('account_locked', 'Account Locked'), ('other', 'Other')], db_index=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(default=dict, help_text='Additional event details')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Event',
                'verbose_name_plural': 'Security Events',
                'db_table': 'security_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='security_ev_event_t_33b3e5_idx'), models.Index(fields=['user', '-created_at'], name='security_ev_user_id_c77a93_idx'), models.Index(fields=['ip_address', '-created_at'], name='security_ev_ip_addr_48a73a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('job_application', 'Job Application'), ('application_status', 'Application Status Update'), ('job_posted', 'Job Posted'), ('job_expiring', 'Job Expiring Soon'), ('application_deadline', 'Application Deadline Reminder'), ('new_job_match', 'New Job Match'), ('message', 'Message'), ('system', 'System Notification'), ('other', 'Other')], db_index=True, help_text='Type of notification', max_length=50)),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', help_text='Notification priority', max_length=20)),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Whether notification has been read')),
                ('read_at', models.DateTimeField(blank=True, help_text='When notification was read', null=True)),
                ('action_url', models.URLField(blank=True, help_text='URL to navigate to when notification is clicked')),
                ('related_object_type', models.CharField(blank=True, help_text='Type of related object (e.g., job, application)', max_length=50)),
                ('related_object_id', models.IntegerField(blank=True, help_text='ID of related object', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional notification metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_c4e471_idx'), models.Index(fields=['user', 'notification_type', '-created_at'], name='notificatio_user_id_770179_idx'), models.Index(fields=['priority', '-created_at'], name='notificatio_priorit_b3d0b6_idx')],
            },
        ),
        migrations.CreateModel(
            name='IPWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address to whitelist')),
                ('description', models.CharField(blank=True, help_text='Description of why this IP is whitelisted', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this whitelist entry is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this whitelist entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ip_whitelists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IP Whitelist',
                'verbose_name_plural': 'IP Whitelists',
                'db_table': 'ip_whitelist',
                'indexes': [models.Index(fields=['ip_address', 'is_active'], name='ip_whitelis_ip_addr_2d21a4_idx')],
                'unique_together': {('ip_address',)},
            },
        ),
        migrations.CreateModel(
            name='ChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='ID of object')),
                ('field_name', models.CharField(help_text='Name of the field that changed', max_length=100)),
                ('old_value', models.TextField(blank=True, help_text='Old value (serialized)')),
                ('new_value', models.TextField(blank=True, help_text='New value (serialized)')),
                ('change_reason', models.TextField(blank=True, help_text='Reason for the change')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who made the change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_history', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(help_text='Type of object', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Change History',
                'verbose_name_plural': 'Change Histories',
                'db_table': 'change_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id', '-created_at'], name='change_hist_content_19526e_idx'), models.Index(fields=['changed_by', '-created_at'], name='change_hist_changed_0aeae7_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('login', 'Login'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('permission_change', 'Permission Change'), ('status_change', 'Status Change'), ('other', 'Other')], db_index=True, help_text='Action performed', max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of object affected', null=True)),
                ('object_repr', models.CharField(help_text='String representation of the object', max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Changes made (field: {old: value, new: value})')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='User agent string', max_length=255)),
                ('request_path', models.CharField(blank=True, help_text='API endpoint or URL path', max_length=500)),
                ('request_method', models.CharField(blank=True, help_text='HTTP method (GET, POST, etc.)', max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='Type of object affected', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action (null for system actions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='audit_logs_user_id_6193b2_idx'), models.Index(fields=['action', '-created_at'], name='audit_logs_action_bcaa71_idx'), models.Index(fields=['content_type', 'object_id'], name='audit_logs_content_b0ef47_idx'), models.Index(fields=['-created_at'], name='audit_logs_created_43fcd6_idx')],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for the API key', max_length=255)),
                ('key', models.CharField(db_index=True, help_text='The API key (hashed)', max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this API key is active')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time this key was used', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Expiration date (null = never expires)', null=True)),
                ('rate_limit', models.PositiveIntegerField(default=1000, help_text='Rate limit per hour for this key')),
                ('allowed_ips', models.TextField(blank=True, help_text='Comma-separated list of allowed IP addresses (empty = all)')),
                ('scopes', models.JSONField(default=list, help_text='List of allowed scopes/permissions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns this API key', on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'db_table': 'api_keys',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['key', 'is_active'], name='api_keys_key_9cfb4a_idx'), models.Index(fields=['user', 'is_active'], name='api_keys_user_id_6e7352_idx')],
            },
        ),
    ]
